services:
  - type: web
    name: sdsmanager-backend
    runtime: python
    rootDir: backend
    pythonVersion: "3.11.0"
    buildCommand: pip install -r requirements.txt && python -m spacy download en_core_web_sm
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ALGORITHM
        value: HS256
      - key: BASE_URL
        sync: false