/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SdsRouteImport } from './routes/sds'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as QrCodesRouteImport } from './routes/qr-codes'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SdsIdRouteImport } from './routes/sds_.$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SdsRoute = SdsRouteImport.update({
  id: '/sds',
  path: '/sds',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const QrCodesRoute = QrCodesRouteImport.update({
  id: '/qr-codes',
  path: '/qr-codes',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SdsIdRoute = SdsIdRouteImport.update({
  id: '/sds_/$id',
  path: '/sds/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/library': typeof LibraryRoute
  '/locations': typeof LocationsRoute
  '/qr-codes': typeof QrCodesRoute
  '/reports': typeof ReportsRoute
  '/risk': typeof RiskRoute
  '/sds': typeof SdsRoute
  '/search': typeof SearchRoute
  '/sds/$id': typeof SdsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/library': typeof LibraryRoute
  '/locations': typeof LocationsRoute
  '/qr-codes': typeof QrCodesRoute
  '/reports': typeof ReportsRoute
  '/risk': typeof RiskRoute
  '/sds': typeof SdsRoute
  '/search': typeof SearchRoute
  '/sds/$id': typeof SdsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/library': typeof LibraryRoute
  '/locations': typeof LocationsRoute
  '/qr-codes': typeof QrCodesRoute
  '/reports': typeof ReportsRoute
  '/risk': typeof RiskRoute
  '/sds': typeof SdsRoute
  '/search': typeof SearchRoute
  '/sds_/$id': typeof SdsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compliance'
    | '/library'
    | '/locations'
    | '/qr-codes'
    | '/reports'
    | '/risk'
    | '/sds'
    | '/search'
    | '/sds/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compliance'
    | '/library'
    | '/locations'
    | '/qr-codes'
    | '/reports'
    | '/risk'
    | '/sds'
    | '/search'
    | '/sds/$id'
  id:
    | '__root__'
    | '/'
    | '/compliance'
    | '/library'
    | '/locations'
    | '/qr-codes'
    | '/reports'
    | '/risk'
    | '/sds'
    | '/search'
    | '/sds_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComplianceRoute: typeof ComplianceRoute
  LibraryRoute: typeof LibraryRoute
  LocationsRoute: typeof LocationsRoute
  QrCodesRoute: typeof QrCodesRoute
  ReportsRoute: typeof ReportsRoute
  RiskRoute: typeof RiskRoute
  SdsRoute: typeof SdsRoute
  SearchRoute: typeof SearchRoute
  SdsIdRoute: typeof SdsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sds': {
      id: '/sds'
      path: '/sds'
      fullPath: '/sds'
      preLoaderRoute: typeof SdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-codes': {
      id: '/qr-codes'
      path: '/qr-codes'
      fullPath: '/qr-codes'
      preLoaderRoute: typeof QrCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sds_/$id': {
      id: '/sds_/$id'
      path: '/sds/$id'
      fullPath: '/sds/$id'
      preLoaderRoute: typeof SdsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComplianceRoute: ComplianceRoute,
  LibraryRoute: LibraryRoute,
  LocationsRoute: LocationsRoute,
  QrCodesRoute: QrCodesRoute,
  ReportsRoute: ReportsRoute,
  RiskRoute: RiskRoute,
  SdsRoute: SdsRoute,
  SearchRoute: SearchRoute,
  SdsIdRoute: SdsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
